### PR TITLE
plugin system

### PR DESCRIPTION
**Pull request by bitjson**

### CODE REVIEW

**Comment by ajliu** [comment]
in `package.json` can you replace statements in scripts containing semicolons with a single ampersand? They are functionally the same but more operating systems support the ampersand.

``` json
    "install": "npm run install-tooling & cordova prepare",
    "install-tooling": "npm run install-hooks & npm run install-starter & npm run install-simserver",
    ...
    "clean": "rm -rf node_modules & rm -rf platforms & rm -rf plugins"
```

**Comment by ajliu** [comment]
Another small change: in `develop.js` the child_process package is known to not run properly on windows. There's drop-in shim called [cross-spawn](https://www.npmjs.com/package/cross-spawn), which just requires a change in the dependencies and a require statement.

```
var spawn = require('cross-spawn');
```

as apposed to

```
var spawn = require('child_process');
```

**Comment by bitjson** [comment]
@AJLiu thanks, I updated the scripts with `;`s. 

Could you confirm that `npm start` still fails on windows without `cross-spawn`? I set up a workaround for https://github.com/s-panferov/awesome-typescript-loader/issues/102, so it should be running properly out of the box with `npm install && npm start`. The more dependencies we can avoid (particularly top-level) the better.

**Comment by ajliu** [comment]
The npm start issue persists.
I looked into it and found that you need to have the extension of npm for it to run on windows, and I made a pull request to your repo.
https://github.com/bitjson/icv2/pull/1

**Comment by bitjson** [comment]
@AJLiu thanks!

**Pull request merged**
